version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: deps
    # Ignore regular version updates for all direct dependencies except
    # github.com/coredns/coredns and github.com/0xERR0R/blocky.
    # Security updates still apply to all packages because update-types
    # in ignore conditions do not affect security updates.
    ignore:
      - dependency-name: "github.com/coredns/caddy"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "github.com/miekg/dns"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "github.com/prometheus/client_golang"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "github.com/prometheus/client_model"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "golang.org/x/sync"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
